CREATE TABLE POLICY_INFO
(
    POLICY_NO      VARCHAR2(50) NOT NULL,
    APPLICATION_NO VARCHAR2(50) NOT NULL,
    APPLY_DATE     DATE         NOT NULL,
    EFFECTIVE_DATE DATE         NOT NULL,
    POLICY_STATUS  VARCHAR2(1)  NOT NULL,
    CREATED_BY     VARCHAR2(20) DEFAULT USER,
    CREATED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY     VARCHAR2(20) DEFAULT USER,
    UPDATED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_POLICY_INFO PRIMARY KEY (POLICY_NO),
    CONSTRAINT UK_POLICY_INFO__APPLICATION_NO UNIQUE (APPLICATION_NO)
);

COMMENT ON TABLE POLICY_INFO IS '保单主信息表';
COMMENT ON COLUMN POLICY_INFO.POLICY_NO IS '保单号';
COMMENT ON COLUMN POLICY_INFO.APPLICATION_NO IS '投保单号';
COMMENT ON COLUMN POLICY_INFO.APPLY_DATE IS '投保日期';
COMMENT ON COLUMN POLICY_INFO.EFFECTIVE_DATE IS '保单生效时间';
COMMENT ON COLUMN POLICY_INFO.POLICY_STATUS IS '保单状态';
COMMENT ON COLUMN POLICY_INFO.CREATED_BY IS '创建人';
COMMENT ON COLUMN POLICY_INFO.CREATED_AT IS '创建时间';
COMMENT ON COLUMN POLICY_INFO.UPDATED_BY IS '更新人';
COMMENT ON COLUMN POLICY_INFO.UPDATED_AT IS '更新时间';
