CREATE TABLE PLAN_TBL (
    PLAN_CODE       VARCHAR2(10)           NOT NULL,
    PLAN_NAME       VARCHAR2(200)          NOT NULL,
    UNIT_SUM        CHAR(1)                NOT NULL,
    UNIT_PRICE      NUMBER(16, 4)          NOT NULL,
    SALE_START_DATE DATE,
    SALE_END_DATE   DATE,
    STATUS          NUMBER(1)    DEFAULT 1 NOT NULL,
    CREATED_BY      VARCHAR2(20) DEFAULT USER,
    CREATED_AT      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY      VARCHAR2(20) DEFAULT USER,
    UPDATED_AT      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PLAN_TBL PRIMARY KEY (PLAN_CODE),
    CONSTRAINT CHK_PLAN_TBL__UNIT_SUM CHECK (UNIT_SUM IN ('U', 'S')),
    CONSTRAINT CHK_PLAN_TBL__STATUS CHECK (STATUS IN (0, 1))
);

-- 添加注释
COMMENT ON TABLE PLAN_TBL IS '险种表';
COMMENT ON COLUMN PLAN_TBL.PLAN_CODE IS '险种代码';
COMMENT ON COLUMN PLAN_TBL.PLAN_NAME IS '险种名称';
COMMENT ON COLUMN PLAN_TBL.UNIT_SUM IS '计费类型: U-份数型, S-保额型';
COMMENT ON COLUMN PLAN_TBL.UNIT_PRICE IS '1份价格';
COMMENT ON COLUMN PLAN_TBL.SALE_START_DATE IS '起售日期';
COMMENT ON COLUMN PLAN_TBL.SALE_END_DATE IS '停售日期';
COMMENT ON COLUMN PLAN_TBL.STATUS IS '状态: 1-有效, 0-无效';
COMMENT ON COLUMN PLAN_TBL.CREATED_BY IS '创建人';
COMMENT ON COLUMN PLAN_TBL.CREATED_AT IS '创建时间';
COMMENT ON COLUMN PLAN_TBL.UPDATED_BY IS '更新人';
COMMENT ON COLUMN PLAN_TBL.UPDATED_AT IS '更新时间';
