CREATE TABLE PREM_RATE_TBL
(
    PLAN_CODE      VARCHAR2(20)  NOT NULL,
    GENDER         VARCHAR2(1)   NOT NULL,
    AGE            NUMBER(3)     NOT NULL,
    PAYMENT_PERIOD NUMBER(3)     NOT NULL,
    COVERAGE_PERIOD NUMBER(3)    NOT NULL,
    PLAN_STATUS    VARCHAR2(1)   NOT NULL,
    ANNUAL_PREMIUM NUMBER(20, 2) NOT NULL,
    CONSTRAINT PK_PREM_RATE_TBL PRIMARY KEY (PLAN_CODE, GENDER, AGE, PAYMENT_PERIOD, COVERAGE_PERIOD, PLAN_STATUS)
);

COMMENT ON TABLE PREM_RATE_TBL IS '费率表';
COMMENT ON COLUMN PREM_RATE_TBL.PLAN_CODE IS '险种代码';
COMMENT ON COLUMN PREM_RATE_TBL.GENDER IS '性别:M-男;F-女';
COMMENT ON COLUMN PREM_RATE_TBL.AGE IS '被保人年龄';
COMMENT ON COLUMN PREM_RATE_TBL.PAYMENT_PERIOD IS '缴费年期';
COMMENT ON COLUMN PREM_RATE_TBL.COVERAGE_PERIOD IS '保障年期';
COMMENT ON COLUMN PREM_RATE_TBL.PLAN_STATUS IS '保单状态';
COMMENT ON COLUMN PREM_RATE_TBL.ANNUAL_PREMIUM IS '年交保费';