DELETE FROM PLAN_TBL WHERE PLAN_CODE = '100';

INSERT INTO PLAN_TBL (PLAN_CODE, PLAN_NAME, UNIT_SUM, UNIT_PRICE, SALE_START_DATE, SALE_END_DATE, STATUS)
VALUES ('100', '康乐一生重大疾病保险（100款）', 'S', 10000, TO_DATE('2020-01-01', 'YYYY-MM-DD'), NULL, 1);
