/* 以 SYSTEM 用户执行 */
-- 创建用户、指定密码
CREATE USER INSURANCE_USER IDENTIFIED BY "123456";
-- 赋予权限：连接数据库和创建会话。
GRANT CONNECT, RESOURCE TO INSURANCE_USER;
-- 创建表空间`APHRODITE_TS`，初始100M，满了以后10M自增。指定构成该表空间的【物理文件】`aphrodite_ts_01.dbf`
CREATE TABLESPACE APHRODITE_TS
    DATAFILE 'aphrodite_ts_01.dbf' SIZE 100M
    AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;
-- 设置默认表空间
ALTER USER INSURANCE_USER DEFAULT TABLESPACE APHRODITE_TS;
-- 赋予权限：在默认表空间中存储数据的配额为 UNLIMITED（无限制）。
ALTER USER INSURANCE_USER QUOTA UNLIMITED ON APHRODITE_TS;
-- 赋予权限：创建视图
GRANT CREATE VIEW TO INSURANCE_USER;
